Runnect/Runnect-Server

- src/module/convert/requestConvertDeparture.ts
requestConvertDeparture 함수 만들었습니다.
---
departureAddress, departureName을 string으로 받아서 
departureObject (region, city, town, detail, name) 만들어 return 했습니다!
---
- 
-
---
> [Feat] requestConvertDeparture

- src/constant/responseMessage.ts
- src/controller/index.ts
- src/controller/publicCourseController.ts
- src/index.ts
- src/interface/DTO/PublicCourseCreateDTO.ts
- src/module/convert/convertDataForm.ts
- src/module/convert/convertDateForm.ts
- src/module/convert/convertTime.ts
- src/prisma/schema.prisma
- src/router/index.ts
- src/router/publicCourseRouter.ts
- src/service/index.ts
- src/service/publicCourseService.ts
---
closes #10 
time을 db에 넣고 뺄때 쓰는 함수
---
- dayjs 사용
---
> [Feat] convert time

- src/controller/publicCourseController.ts
- src/module/convert/convertTime.ts
- src/router/publicCourseRouter.ts
- src/service/publicCourseService.ts
---
colses #7 
---
- 1차로 express-validator를 사용해 request에 들어있어야할 검사를 하고 그 error 메시지를 이용해 400 분기처리
- 2차로 prisma 를 이용해 create 문을 실행하고, prisma의 error 메시지를 이용해 400 분기처리
---
> [ Feat ] createPublicCourse

- src/controller/publicCourseController.ts
- src/interface/DTO/PublicCourseCreateDTO.ts
- src/service/publicCourseService.ts
> Chore git setting

- src/constant/responseMessage.ts
- src/controller/publicCourseController.ts
- src/interface/DTO/PublicCourseGetDTO.ts
- src/router/publicCourseRouter.ts
- src/service/publicCourseService.ts
---
closes #14 
---
- machineId를 헤더에 받아와
- include를 사용해, machineId, private false인 course 테이블에 publicCourse를 조인해 값을가져옴
---
prisma include 를 사용해 sql 조인을 구현함
> [Feat]getPublicCourseByUser

- src/constant/responseMessage.ts
- src/controller/courseController.ts
- src/interface/DTO/PrivateCourseGetDTO.ts
- src/router/courseRouter.ts
- src/service/courseService.ts
---
closes #21 
---
- machineId를 헤더에 받아와 
- 해당하는 유저가 그린 코스 중 private - true인 코스들을 최신순으로 정렬하여 가져온다.
---
> [Feat] getPrivateCourseByUser

- src/constant/responseMessage.ts
- src/controller/publicCourseController.ts
- src/interface/DTO/PublicCourseGetDTO.ts
- src/module/check/checkScrap.ts
- src/router/publicCourseRouter.ts
- src/service/publicCourseService.ts
---
closes #17 
---
- express-validator 로 prams와 headers를 검사해 타입과 req required data 유무 검사 -> 검사결과로 에러 분기처리
- interface/DTO/PublicCourseGetDTO에 PublicCourseDetailGetDTO interface를 만듬
- include를 이용해, PublicCourse, Course, User, Scrap 4개의 테이블 조인해 결과를 가져옴
- 결과가 없는 경우는 publicCourseId가 잘못된것(테이블에 없는 아이디)인것이므로 에러처리
- 스크랩 유무를 명확히 하기위해 module/check/checkScrap.ts 를 만들어 prisma output으로부터 현재 사용자가 해당 퍼블릭코스에 스크랩을 했는지 안했는지 검사하는 함수를 만듬
---
> [Feat]  getPublicCourseDetail

- src/constant/responseMessage.ts
- src/controller/publicCourseController.ts
- src/interface/DTO/PublicCourseGetDTO.ts
- src/module/check/checkScrap.ts
- src/router/publicCourseRouter.ts
- src/service/publicCourseService.ts
---
closes #27 
---
- express-validator를 이용한 parms 에러분기처리
- prisma에서 구현된 groupby를 쓰려했지만 join-select를 한번에 쓸수없어, findMany에 publicCourse pk 값인 id 단위로 count 함수를 구현하며 groupby-count-join-select와 같은 기능을 구현
- 기존에 만든 publicCourseDto와 map 함수를 이용하여 response 형식 구현
---
> [Feat]RecommendPublicCourse

- src/constant/responseMessage.ts
- src/controller/publicCourseController.ts
- src/interface/DTO/PublicCourseGetDTO.ts
- src/module/check/checkScrap.ts
- src/router/publicCourseRouter.ts
- src/service/publicCourseService.ts
---
closes #29 
---
- express-validator를 사용해 헤더의 기기넘버, 쿼리의 검색어 에러분기처리
- publicCourse의 include(join), contain, or를 사용해 검색기능 구현
- 기존 dto를 사용해 response 구현
---
> [Feat]SearchPublicCourse

- src/service/index.ts
- src/service/stampService.ts
---
closes #23 
---
- 옵션에 해당하는 활동 횟수 가져옴
- 활동 횟수에 따라 얻게 되는 스탬프 넘버 구함
- 스탬프 업데이트 & 유저 테이블의 최신 스탬프 업데이트
- 레벨 업데이트
---
- db에 최대한 적게 접속할 수 있도록 짜긴 했는데 좋은 생각있으면 말해주세여,,
> [Feat] createStampByUser

- src/interface/DTO/PrivateCourseGetDTO.ts
- src/service/courseService.ts
---
closes #35 
---
- DTO 변경
- service 단에서 detail 제거
---
> [Fix] getPrivateCourseByUser DTO 변경

- src/controller/index.ts
- src/controller/userController.ts
- src/router/index.ts
- src/router/userRouter.ts
- src/service/index.ts
- src/service/userService.ts
---
closes #40 
---
- machineId와 nickname을 받아 새로운 유저를 생성했다.
---
> [Feat] signUp

- src/constant/responseMessage.ts
- src/controller/userController.ts
- src/interface/DTO/UserGetDTO.ts
- src/router/userRouter.ts
- src/service/userService.ts
---
closes #42 
---
- request header를 통해 machineid를 받아 일치하는 유저를 조회한다.
- 해당 유저의 획득 스탬프 개수를 조회하여 levelPercent를 계산하여 유저 정보와 함께 response한다.
---
> [Feat] getUser

- src/constant/responseMessage.ts
- src/controller/userController.ts
- src/interface/DTO/UpdatedUserGetDTO.ts
- src/router/userRouter.ts
- src/service/userService.ts
---
closes #45 
---
- request에서 받아온 machineId와 변경할 닉네임을 이용하여 machineId에 해당하는 유저의 닉네임을 변경하고 modified_at을 업데이트 한다.
---
> [Feat] updateUserNickname

- src/constant/responseMessage.ts
- src/controller/courseController.ts
- src/interface/DTO/CourseDetailGetDTO.ts
- src/router/courseRouter.ts
- src/service/courseService.ts
---
closes #37 
---
- request에서 machineId, courseId를 받아온다.
- courseId에 해당하는 코스의 디테일한 정보를 유저 정보와 함께 넘겨준다.
---
> [Feat] getCourseDetail

- src/controller/courseController.ts
- src/middleware/auth.ts
- src/middleware/index.ts
- src/middleware/multiformDataConvert.ts
- src/module/jwtHandler.ts
- src/router/courseRouter.ts
---
closes #51 
---
- multipart-form data로  req가 올때 json 형식으로 데이터를 data에 담아 보내면
- 해당 데이터를 JSON.parese를 통해 object로 파싱하고
- 해당 객체 안의 정보들을 다시 req.body에 뿌려 express-validator를 사용 가능하게 함
---
> Fix/#51 parseJsonMiddlewareCreate

- src/constant/responseMessage.ts
- src/controller/index.ts
- src/controller/publicCourseController.ts
- src/controller/stampController.ts
- src/interface/DTO/StampGetDTO.ts
- src/middleware/auth.ts
- src/module/jwtHandler.ts
- src/router/index.ts
- src/router/stampRouter.ts
- src/service/stampService.ts
---
closes #31 
---
- 기기넘버를 express validator로 에러분기처리
- machineId를 가지고 UserStamp 테이블에서 유저의 스탬프를 가져오기, 이때, 스탬프 아이디를 사전순으로 정렬해 가져옴
---
> [Feat]get stamp by user

- src/controller/publicCourseController.ts
- src/interface/DTO/publicCourse/PublicCourseGetDTO.ts
- src/middleware/multiformDataConvert.ts
> 🐛 fix: tsc 컴파일 에러 해결

- src/interface/DTO/course/CourseDetailGetDTO.ts
- src/service/courseService.ts
#61
---
closes #61
---
- dto 수정
- image도 받아옴
---
> 🐛 fix: response로 image 추가 완료 (#61)

- src/service/courseService.ts
#66
---
closes #66 
---
- distance Number로 type casting함
---
> 🐛 fix: distance type 변경 (#66)

- src/index.ts
- test/record.spec.js
#65
---
issues #65
---
- record api관련 test code 작성
---
> [Test] recordTestCode

- src/index.ts
- test/record.spec.js
- test/scrap.spec.js
---
issues #70
---
- scrap api관련 test code 작성
---
> [Test] scrapTestCode

- src/controller/scrapController.ts
- src/service/courseService.ts
- src/service/publicCourseService.ts
- src/service/stampService.ts
- test/user.spec.js
---
close #74 
---
- 회원가입, 마이페이지, 닉네임 변경 api 각각의 test code 작성
---
> [Test] user Test code

- .husky/pre-push
- src/module/randomInitialNickname.ts
- test/user.spec.js
---
closes #96 
---
- 
- 9자리의 영문+숫자 랜덤 문자열을 생성하고 그 앞에 '임시'라는 단어를 붙임
---
이 함수를 사용하여 소셜로그인으로 처음 회원가입시 닉네임에 넣으면 될듯
> [Feat] random initial nickname

- src/controller/authController.ts
- src/module/social.ts
---
closes #98 
---
- 전달받은 토큰을 jwt로 디코딩해 원하는 정보 추출
-
---
> [Feat] appleSocialLogin

- e -i -p ad3ab28
- src/constant/responseMessage.ts
- src/controller/recordController.ts
- src/router/recordRouter.ts
- src/service/recordService.ts
#128
---
closes #128 
---
- request로 recordId와 수정할 title 내용을 받는다.
- request값을 활용하여 활동 기록의 제목을 수정한다.
---
> [Feat] updateRecord

- src/constant/responseMessage.ts
- src/controller/recordController.ts
- src/router/recordRouter.ts
- src/service/recordService.ts
---
closes #134 
다중삭제로 다시 수정했습니다!!
---
- 레코드 삭제 라우터, 컨트롤러, 서비스 작성
- 레코드 삭제 시 삭제된 레코드 아이디 갯수 반환
- Array<number> 타입으로 삭제할 레코드 아이디들 받음
---
> [Feat] deleteRecord

- src/controller/userController.ts
- src/router/userRouter.ts
- src/service/userService.ts
---
closes #138 
---
- header에서 refreshToken 받아옴
- getUserByRefreshToken함수를 통해서 user 찾고
- 해당 userId를 사용하여 유저 삭제
---
> [Feat] deleteUser

- src/constant/responseMessage.ts
- src/service/scrapService.ts
---
closes #158
---
- 스크랩하려는 유저와 퍼블릭 코스 작성자의 아이디를 대조하는 로직 삭제
-
---
> [FIX] 본인 public course 스크랩 기능 추가

- prisma/schema.prisma
- src/middleware/auth.ts
fix #175
---
closes #175 
---
- auth미들웨어에서 accessToken=="visitor", refreshToken == "null"일 때 임의로 userId값을 0으로 넘겨 방문자를 구분하였습니다.
---
- 유저 생성/탈퇴를 반복해도 userId가 0이 될 수 없으므로 방문자일 때 임의로 넘겨주는 값을 0으로 결정했습니다!
> [Fix] apiModifyForVisitorMode

- prisma/schema.prisma
- src/service/courseService.ts
- src/service/publicCourseService.ts
- src/service/recordService.ts
- src/service/scrapService.ts
- src/service/stampService.ts
---
closes #173 
---
- 유저 테이블에 필드 추가 -> createdCourse, createdPublicCourse, createdScrap, createdRecord
- createCourse, createRecord, createPubilcCourse, creatScrap 시마다 User의 해당 컬럼 업데이트 (ex. createCourse -> createdCourse +1)
- 스탬프 서비스에서 getCount -> user 테이블에서 읽어오는 걸로 변경
---
> [Feat] changeStampSystem

- src/module/social.ts
> ✨ feat: 클라이언트 아이디 추가 (#189)

- dist/controller/publicCourseController.js
- src/controller/publicCourseController.ts
> Build# dist
